### ISSUE TITLE
actions/jekyll-build-pages is too simple to satisfy Gemfile dependencies

### ISSUE THREAD

**Issue by matthewfeickert** [UW-Madison-DSI/ospo.wisc.edu#11]
The current CI build

https://github.com/UW-Madison-DSI/ospo.wisc.edu-uw-jekyll-theme/blob/d306594937dd2637b8ede4127519b41734725f17/.github/workflows/jekyll-gh-pages.yml#L29-L30

has the warning:

> The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/

From looking at https://github.com/actions/jekyll-build-pages/blob/2b9a1ccfebe79720f5512bbfcb5358d27c5426bf/action.yml it looks like https://github.com/actions/jekyll-build-pages is too simple and setting up Ruby similar to how IRIS-HEP does in https://github.com/iris-hep/iris-hep.github.io/blob/293b76a79e76c1d84d3d448ba2476d3fd0c99767/.github/workflows/deploy.yml will be required.

**Comment by cranmer** [comment]
These issues and PRs are all great, but I wanted to note that they should make their way back upstream to 
https://github.com/UW-Madison-DSI/uw-jekyll-theme

**Comment by matthewfeickert** [comment]
@cranmer Sounds good, though can you comment on what the plan is for the UW (https://github.com/UW-Madison-DSI/uw-jekyll-theme) vs. the OSPO (https://github.com/UW-Madison-DSI/ospo.wisc.edu-uw-jekyll-theme) themes? I'm not fully clear on why the OSPO theme is a fork given that it seems to have deviated significantly. Was the OSPO theme supposed to be a specific implementation of the UW theme? Or is there a plan to reunify them in the future?

**Comment by cranmer** [comment]
Yes, the original plan was that the ospo site would be a fork of the generic uw-jekyll-theme. I was hoping all the core uw-jekyll-theme changes would have already been made, but in reality many of the changes to the theme have been done in the ospo site. Once we clean it up, I'd like to advertise the uw-jekyll-theme for people at UW more generally. I also would like my cranmer-lab site to be based on that uw-jekyll-theme as well (but that also has an inverted time ordering).

**Comment by matthewfeickert** [comment]
Thanks. This all helps put things in a more clear perspective.

I think that creating a `cookiecutter` (or maybe there is a Ruby equivalent &mdash; a question for Henry probably) makes more sense for achieving what the design goal seems to be here, as otherwise all the projects are tied to each other forever (unless you email GitHub support for each individual repo and ask them to sever the "fork" tie between things). This isn't necessarily "bad", but once projects start to deviate then it can start to become a bit strange to have large deviations in the commit history from the parent project and the fork if there isn't any plan for reunification in the future.

Though all of this is discussion for the future too. :)

**Comment by cranmer** [comment]
Yeah, I agree, but it seems to be the pattern used in the original al-folio project
https://github.com/alshedivat/al-folio


It is a bit of a mess for distributing new features from al-folio as well.
