### ISSUE TITLE
"Open Sourcing the Wisconsin Idea" tagline

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/ospo.wisc.edu#13]
We used to have the "Open Sourcing the Wisconsin Idea" tagline below the main OSPO header. I liked that. Now it says "@ the Data Science Institute", which I'm less fond of. 

I would suggest we go back to having the tagline next to the crest (but no link to "Wisconsin Idea")

**Comment by amkitt** [comment]
Let's return the tagline to the main header, maybe experiment with not laying any text over the hero image, and add a DSI mention in the second paragraph of the Mission section:

Thanks to a grant from the Alfred P. Sloan Foundation, The University of Wisconsin–Madison Data Science Institute has positioned the Open Source Program Office (OSPO) to support and grow our vibrant open source ecosystem. The OSPO's mission is to collaborate with key stakeholders and community members to provide open source learning opportunities, promote best practices, facilitate the use of open source software in research, and make open source–fueled connections between practitioners and adopters on campus and beyond.

**Comment by cranmer** [comment]
Can we link to Sloan when we mention Sloan Foundation in that text.

I also think it would make sense to incorporate the Sloan logo somewhere on the main page.

**Comment by amegahed** [comment]
Something like this?
![OSPO Sloan Foundation](https://github.com/user-attachments/assets/7d84367a-e288-451d-b214-bed72f7ec42e)
