### ISSUE TITLE
Current deployment process is not deploying the news filter pages.

### ISSUE THREAD

**Issue by amegahed** [UW-Madison-DSI/ospo.wisc.edu#15]
**Describe the bug**
When pushes a change to the repository and the deployment is triggered, the resulting deployment does not include the news filter pages (currently just "Announcements" and "2024").   Previously, these pages could be deployed by running the "deploy.sh" al-folio script.

**To Reproduce**
1. Push a change to the repo.
2. Visit the news page: https://uw-madison-dsi.github.io/ospo.wisc.edu-uw-jekyll-theme/blog/ 
3. Click on "Announcements" or "2024"
4. You will see the "Page not found" error.

This may be a duplicate / byproduct of:
https://github.com/UW-Madison-DSI/ospo.wisc.edu-uw-jekyll-theme/issues/11 

Our current deployment seems to have departed from the al-folio "Recommended Approach" of creating a "gh-pages" branch:
https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#recommended-approach

**Comment by matthewfeickert** [comment]
> Our current deployment seems to have departed from the al-folio "Recommended Approach" of creating a "gh-pages" branch:
> https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#recommended-approach

These (https://github.com/alshedivat/al-folio/blob/1d4ce5a313d1c41e73c843587692eabebad96e00/INSTALL.md#recommended-approach) use a old design pattern that isn't recommended anymore as a best approach. It isn't wrong as GitHub hasn't removed support yet, but it isn't something to use in new projects.
