### ISSUE TITLE
horizontal margins for UW shield and header

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/ospo.wisc.edu#16]
The OSPO website seems to have much smaller horizontal margins in general, but it's most noticeable when navigating between DSI and OSPO webpages where the location of the UW shield and header are in very different locations. 

<img width="1340" alt="image" src="https://github.com/user-attachments/assets/a8a82cdb-ccf2-4147-8d4f-795eded7a38e">

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/79d4d80a-9fa8-4771-b6e0-682e7e7417cb">

**Comment by amegahed** [comment]
The margins match now.  The typography is close but doesn't 100% match. 

DSI website:
<img width="600" alt="dsi-website" src="https://github.com/user-attachments/assets/58dfd2e6-c751-4da3-ada6-3486d345f551">
OSPO website:
<img width="600" alt="ospo-website" src="https://github.com/user-attachments/assets/2e7f3576-b9d2-4cf0-939b-2b7225b2f6b4">
