### ISSUE TITLE
Homepage header update

### ISSUE THREAD

**Issue by amkitt** [UW-Madison-DSI/ospo.wisc.edu#2]
Retool site header image in a format similar to dsi.wisc.edu. Header text over image could be where "open sourcing the Wisconsin Idea" slogan goes. Image wise I've linked some that may make a good header, feel free to recommend alternatives!
https://uwmadison-photos.photoshelter.com/search/result/I0000RRyQDZpsJAM?terms=neon&
https://uwmadison-photos.photoshelter.com/search/result/I0000lz5ppcmoc6E?terms=&
https://uwmadison-photos.photoshelter.com/search/result/I0000poZWmMFyLQ4?terms=alumni%20park%20wall&

**Comment by amegahed** [comment]
Is this more like what you had in mind:
![Open-Source-Program-Office](https://github.com/user-attachments/assets/f3ca923b-8fa0-44e5-af91-44060684eb1d)

**Comment by amegahed** [comment]
Is this more like what you had in mind:
![Open-Source-Program-Office](https://github.com/user-attachments/assets/41959426-523d-4730-8129-86b91203888f)

**Comment by amegahed** [comment]
Is this more like what you had in mind?
![Open-Source-Program-Office](https://github.com/user-attachments/assets/8baefae1-379c-4bd4-b881-c5fb2f8d86b0)

**Comment by amkitt** [comment]
Yes, I think that looks good! It might be good to up the contrast a bit so the text is easier to read, and then we can take the tagline out from under the logo. Thanks!
