### ISSUE TITLE
responsive problems with hero image 

### ISSUE THREAD

**Issue by cranmer** [UW-Madison-DSI/ospo.wisc.edu#21]
The hero image seems to have a minimum width. On mobile or on desktop with a narrow window, the image sticks out to the right beyond the header and leads to a horizontal scroll bar. 

<img width="260" alt="image" src="https://github.com/user-attachments/assets/989a6549-614e-4a9a-9d8c-6ec3ae52780b">

<img width="308" alt="image" src="https://github.com/user-attachments/assets/854955c9-1648-46d6-ad95-c0baee3edaf5">

**Comment by amegahed** [comment]
Reworked hero image layout to avoid having to use this kludgy workaround:
https://github.com/sass/libsass/issues/104

**Comment by cranmer** [comment]
I’m a little confused because I thought that the initial UW theme that we started with would have dealt with this properly. Are we not using their code for that or did that just have this problem?
