### ISSUE TITLE
Team page update

### ISSUE THREAD

**Issue by amkitt** [UW-Madison-DSI/ospo.wisc.edu#3]
Update teams page
-Organize interns into their own section 
-Add OSPO Executive Committee: Cameron Cook (Libaries), Sarah Stevens (Data Science Hub), Perry Govier (Madison College)
-Add OSPO Advisory Board: Doug Bates, Kevin Eliceiri, Lisa Johnston, Sebastian Raschka

**Comment by amegahed** [comment]
Updated:
https://uw-madison-dsi.github.io/ospo.wisc.edu-uw-jekyll-theme/team.html
