### ISSUE TITLE
Footer Update

### ISSUE THREAD

**Issue by amkitt** [UW-Madison-DSI/ospo.wisc.edu#4]
Update site footer with OSPO-relevant links

**Comment by amegahed** [comment]
This could use some detail as to what those OSPO-relevant links should be.   Currently, the footer contains the following links:

COMMUNITY
[Data Science Institute](https://datascience.wisc.edu/institute/)
[Data Science Hub](https://datascience.wisc.edu/hub/)
[School of Computer, Data & Information Sciences](https://cdis.wisc.edu/)

QUICK LINKS
[Coding Meetup](https://datascience.wisc.edu/hub/#dropin)
[Data Science Research Bazaar](https://datascience.wisc.edu/data-science-research-bazaar/)
[Data Science @ UW Newsletter](https://datascience.wisc.edu/newsletter/)

**Comment by amkitt** [comment]
Here's a link update:

COMMUNITY
[Data Science Institute](https://datascience.wisc.edu/institute/)
[Data Science Hub](https://datascience.wisc.edu/hub/)
[UW-Madison Libraries](https://www.library.wisc.edu/)
[CURIOSS](https://curioss.org/)
[NumFocus](https://numfocus.org/)

QUICK LINKS
[Join Our OSPO Google Group](ospo@g-groups.wisc.edu)
[Data Science Research Bazaar](https://datascience.wisc.edu/data-science-research-bazaar/)
[Data Science @ UW Newsletter](https://datascience.wisc.edu/newsletter/)
